export const LOCAL_STORAGE_THEME_KEY = 'theme'
export const LOCAL_STORAGE_PALETTE_KEY = 'palette'
export const USER_LOCAL_STORAGE_KEY = 'user'
export const TOKEN_LOCAL_STORAGE_KEY = 'token'
export const LOCAL_STORAGE_DIALOG_LAYOUT_KEY = 'dialog_layout'
